name: Bun Application Workflow
on:
    push:
        branches:
            main
jobs:
    bun-jobs:
        name: Running a system   
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - run: bun install
            - run: bun run vite -- dev
