name: Bun Application Workflowon:
    push:
        branches:
            main
jobs:
    bun-jobs:
        name: Building System
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1

            - run: bun install
            - run: bun run vite build
