name: Bun Application Workflow
on:
    push:
        branches:
            main
jobs:
    bun-jobs:
        name: Bun Jobs Runner
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1

            - run: bun install
            - run: cd api
            - run: bun run server.js
